if ! grep ~/.local/bin <<<":$PATH:" >/dev/null
then
	export PATH=~/.local/bin:$PATH
fi

if ! grep ~/.cargo/bin <<<":$PATH:" >/dev/null
then
        export PATH=~/.cargo/bin:$PATH
fi

if ! grep ~/go/bin <<<":$PATH:" >/dev/null
then
    export PATH=~/go/bin:$PATH
fi

if ! grep ~/.node_modules/bin <<<":$PATH:" >/dev/null
then
	export PATH=~/.node_modules/bin:$PATH
fi
export npm_config_prefix=$HOME/.node_modules

export EDITOR=kak
